CREATE DATABASE IF NOT EXISTS curso DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE curso;

CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(100) NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);