{
 "title": "Red Wan  - Region 3 - Centrosur",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Número de interrupciones por dispositivo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Interrupciones",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "10.0.1.1",
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrumpciones",
     "select": [
      [
       { "params": [ "interrupciones" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.1" }
     ]
    },
    {
     "alias": "10.0.1.2",
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrumpciones",
     "select": [
      [
       { "params": [ "interrupciones" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.2" }
     ]
    },
    {
     "alias": "10.0.1.3",
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrumpciones",
     "select": [
      [
       { "params": [ "interrupciones" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.3" }
     ]
    },
    {
     "alias": "10.0.1.4",
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrumpciones",
     "select": [
      [
       { "params": [ "interrupciones" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.4" }
     ]
    },
    {
     "alias": "10.0.1.5",
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interrumpciones",
     "select": [
      [
       { "params": [ "interrupciones" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.5" }
     ]
    }
   ]
  },
  { "title": "Información de dispositivos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Estado</span>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Tiempo de Actividad</span>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Consumo de CPU</span>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Estado</span>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Tiempo de Actividad</span>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "options": {
    "content": "<span style=\"font-size: 20px; font-weight: bold;\">Consumo de CPU</span>\n"
   }
  },
  {
   "title": "10.0.1.1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.1.1" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60480000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.0.1.1" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpupython",
     "select": [
      [
       { "params": [ "uso5min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.1" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.1.4" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60480000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.0.1.4" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpupython",
     "select": [
      [
       { "params": [ "uso5min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.4" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.1.2" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60480000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.0.1.2" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpupython",
     "select": [
      [
       { "params": [ "uso5min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.2" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.1.5" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60480000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.0.1.5" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpupython",
     "select": [
      [
       { "params": [ "uso5min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.5" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "10.0.1.3" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 60480000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "10.0.1.3" }
     ]
    }
   ]
  },
  {
   "title": "10.0.1.3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpupython",
     "select": [
      [
       { "params": [ "uso5min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dispositivo", "operator": "=", "value": "10.0.1.3" }
     ]
    }
   ]
  }
 ]
}